module.exports = [
  {
    name: () => `react-native.config.js`,
    content: ({ exampleName, moduleName }) => `module.exports = {
  dependencies: {
    '${moduleName}': {
      root: __dirname,
    },
  },
  project: {
    android: {
      sourceDir: './${exampleName}/android',
    },
    ios: {
      project: './${exampleName}/ios/${exampleName}.xcworkspace',
    },
  },
};
`,
  },
  {
    name: () => `index.js`,
    content: ({ exampleName }) => `/**
 * This file is an entry point for example app
 */

import { AppRegistry } from 'react-native';
import App from './${exampleName}/App';
import { name as appName } from './${exampleName}/app.json';

AppRegistry.registerComponent(appName, () => App);
`,
  },
  {
    name: ({ exampleName, useTypescript }) => `${exampleName}/App.${useTypescript ? 'tsx' : 'jsx'}`,
    content: ({ moduleName, objectClassName, view }) =>
    `/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import ${objectClassName} from '${moduleName}';` +
    (!view
      ? `

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    ${objectClassName}.sampleMethod('Testing', 123, (message) => {
      this.setState({
        status: 'native callback received',
        message
      });
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆${objectClassName} example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}`
      : `

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆${objectClassName} example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
        <${objectClassName} />
      </View>
    );
  }
}`) +
      `

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
`
  }
];
